<a href="https://colab.research.google.com/github/gagan-bhullar-tech/pytorch/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

## Arrays vs Lists

In [19]:
import numpy as np

In [20]:
L = [1, 2, 3]

In [21]:
A = np.array([1, 2, 3])

In [22]:
for e in L:
  print(e)

1
2
3


In [23]:
for e in A:
  print(e)

1
2
3


In [24]:
L.append(4)

In [25]:
L

[1, 2, 3, 4]

In [26]:
A.append(4)

AttributeError: ignored

In [27]:
L + [5]

[1, 2, 3, 4, 5]

In [ ]:
A + np.array([4])

In [30]:
A + np.array([4, 5, 6])

array([5, 7, 9])

In [29]:
A + np.array([4, 5])

ValueError: ignored

In [31]:
A * 2

array([2, 4, 6])

In [32]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L + L

In [ ]:
L2 = []
for e in L:
  L2.append(e + 3)

In [33]:
L2

[4, 5, 6, 7, 7]

In [34]:
L2 = [e + 3 for e in L]
L2

[4, 5, 6, 7]

In [35]:
L**2

TypeError: ignored

In [36]:
L2 = []
for e in L:
  L2.append(e ** 2)

In [37]:
L2

[1, 4, 9, 16]

In [38]:
A ** 2

array([1, 4, 9])

In [39]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [41]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [42]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [43]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])