<a href="https://colab.research.google.com/github/gagan-bhullar-tech/pytorch/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

## Arrays vs Lists

In [19]:
import numpy as np

In [20]:
L = [1, 2, 3]

In [21]:
A = np.array([1, 2, 3])

In [22]:
for e in L:
  print(e)

1
2
3


In [23]:
for e in A:
  print(e)

1
2
3


In [24]:
L.append(4)

In [25]:
L

[1, 2, 3, 4]

In [26]:
A.append(4)

AttributeError: ignored

In [27]:
L + [5]

[1, 2, 3, 4, 5]

In [ ]:
A + np.array([4])

In [30]:
A + np.array([4, 5, 6])

array([5, 7, 9])

In [29]:
A + np.array([4, 5])

ValueError: ignored

In [31]:
A * 2

array([2, 4, 6])

In [32]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L + L

In [ ]:
L2 = []
for e in L:
  L2.append(e + 3)

In [33]:
L2

[4, 5, 6, 7, 7]

In [34]:
L2 = [e + 3 for e in L]
L2

[4, 5, 6, 7]

In [35]:
L**2

TypeError: ignored

In [36]:
L2 = []
for e in L:
  L2.append(e ** 2)

In [37]:
L2

[1, 4, 9, 16]

In [38]:
A ** 2

array([1, 4, 9])

In [39]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [41]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [42]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [43]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

# dot product

In [45]:
a = np.array([1, 2])
b = np.array([3, 4])

In [46]:
dot = 0
for e, f in zip(a, b):
  dot += e * f
dot

11

In [47]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [48]:
a * b

array([3, 8])

In [49]:
np.sum(a * b)

11

In [50]:
(a * b).sum()

11

In [51]:
np.dot(a, b)

11

In [52]:
a.dot(b)

11

In [53]:
a @ b

11

In [54]:
amag = np.sqrt((a * a).sum())

In [55]:
amag

2.23606797749979

In [56]:
np.linalg.norm(a)

2.23606797749979

In [57]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [59]:
cosangle

0.9838699100999074

In [61]:
angle = np.arccos(cosangle)

In [62]:
angle

0.17985349979247847

# Speed test

In [70]:
# speed comparison

from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e * f
  return result

t0 = datetime.now()

for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0
print(f"dt1: {dt1}, dt2: {dt2}, dt1/dt2: {dt1.total_seconds() / dt2.total_seconds()}")

dt1: 0:00:02.395923, dt2: 0:00:00.076075, dt1/dt2: 31.49422280644101


# matrices

In [71]:
L = [[1, 2], [3, 4]]
L

[[1, 2], [3, 4]]

In [75]:
L[0][1]

2

In [76]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [77]:
A[0][1]

2

In [78]:
A[0, 1]

2

In [84]:
A[:, 0]

array([1, 3])

In [85]:
A.T

array([[1, 3],
       [2, 4]])

In [86]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [87]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [88]:
B = np.array([[1, 2, 3], [4, 5, 6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [91]:
A.dot(B.T)

ValueError: ignored

In [92]:
np.linalg.det(A)

-2.0000000000000004

In [93]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [94]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [95]:
np.trace(A)

5

In [96]:
np.diag(A)

array([1, 4])

In [100]:
np.diag([1, 9])

array([[1, 0],
       [0, 9]])

In [101]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [102]:
Lam, V = np.linalg.eig(A)

In [103]:
V[:, 0] * Lam[0] == A @ V[:, 0]

array([ True, False])

In [106]:
V[:, 0] * Lam[0], A @ V[:, 0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [107]:
np.allclose(V[:, 0] * Lam[0], A @ V[:, 0])

True

In [111]:
np.allclose(V @ np.diag(Lam), A @ V)

True

# Linear equations

In [123]:
A = np.array([[1, 1], [1.5, 4]])
A

array([[1. , 1. ],
       [1.5, 4. ]])

In [127]:
B = np.array([2200, 5050])

In [128]:
X = np.linalg.inv(A) @ B # this is slower
X

array([1500.,  700.])

In [129]:
X = np.linalg.solve(A, B)
X

array([1500.,  700.])