<a href="https://colab.research.google.com/github/gagan0183/pytorch/blob/main/pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch fundamental

```
# This is formatted as code
```



In [158]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introduction to tensors

### Creating tensors

In [159]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [160]:
# Convert tensor to python int
scalar.item()

7

In [161]:
# vector
vector = torch.tensor([9, 9])
vector

tensor([9, 9])

In [162]:
vector.ndim

1

In [163]:
vector.shape

torch.Size([2])

In [164]:
# matrix
MATRIX = torch.tensor([[9, 10], [11, 12]])

In [165]:
MATRIX.ndim

2

In [166]:
MATRIX[0]

tensor([ 9, 10])

In [167]:
MATRIX.shape

torch.Size([2, 2])

In [168]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [9, 5, 6],
                       [9, 9, 9 ]]])

In [169]:
TENSOR.ndim

3

In [170]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors ?

Random tensors are important because the way many netural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random sensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [171]:
# Creata a random tensor of size ( 1, 2)
random_tensor = torch.rand(1, 9, 9)
random_tensor

tensor([[[0.6630, 0.3022, 0.8213, 0.7187, 0.1232, 0.9628, 0.2362, 0.8130,
          0.0553],
         [0.7797, 0.3671, 0.4745, 0.5949, 0.9626, 0.2667, 0.7136, 0.7728,
          0.3961],
         [0.1653, 0.1217, 0.5600, 0.7822, 0.7876, 0.1785, 0.8453, 0.0039,
          0.0405],
         [0.4900, 0.4604, 0.2363, 0.5318, 0.5445, 0.3184, 0.6845, 0.9284,
          0.0016],
         [0.9825, 0.1891, 0.7319, 0.5321, 0.6757, 0.1315, 0.7382, 0.1292,
          0.9411],
         [0.5761, 0.7803, 0.2924, 0.6406, 0.1377, 0.4053, 0.7698, 0.2605,
          0.5971],
         [0.3275, 0.7563, 0.9702, 0.2029, 0.5521, 0.4030, 0.4472, 0.9510,
          0.7742],
         [0.7760, 0.0552, 0.9201, 0.5479, 0.6173, 0.4043, 0.2925, 0.1593,
          0.8189],
         [0.4553, 0.4595, 0.4830, 0.0944, 0.9324, 0.1626, 0.1758, 0.2809,
          0.1664]]])

In [172]:
random_tensor.ndim

3

In [173]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # height, width and color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [174]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (1, 9, 9))
zeros

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [175]:
zeros * random_tensor

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [176]:
# create a tensor of ones
ones = torch.ones(9, 9)
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [177]:
ones.dtype

torch.float32

# Create a range of tensors and tensors-like

In [178]:
# torch.arange()
one_to_ten = torch.arange(start = 1, end = 9000, step = 90)
one_to_ten

tensor([   1,   91,  181,  271,  361,  451,  541,  631,  721,  811,  901,  991,
        1081, 1171, 1261, 1351, 1441, 1531, 1621, 1711, 1801, 1891, 1981, 2071,
        2161, 2251, 2341, 2431, 2521, 2611, 2701, 2791, 2881, 2971, 3061, 3151,
        3241, 3331, 3421, 3511, 3601, 3691, 3781, 3871, 3961, 4051, 4141, 4231,
        4321, 4411, 4501, 4591, 4681, 4771, 4861, 4951, 5041, 5131, 5221, 5311,
        5401, 5491, 5581, 5671, 5761, 5851, 5941, 6031, 6121, 6211, 6301, 6391,
        6481, 6571, 6661, 6751, 6841, 6931, 7021, 7111, 7201, 7291, 7381, 7471,
        7561, 7651, 7741, 7831, 7921, 8011, 8101, 8191, 8281, 8371, 8461, 8551,
        8641, 8731, 8821, 8911])

In [179]:
# tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [180]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # datatype of the sensor e.g. float32, float16 (half)
                               device=None, # device your tensor is on e.g. cpu or cuda 
                               requires_grad=False) # whether or not to compute gradients with this tensor operation
float_32_tensor

tensor([3., 6., 9.])

In [181]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [182]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [183]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get dataype from a tensor - `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor - `tensor.shape`
3. Tensors not on the right device - to get device from a tensor - `tensor.device`

In [184]:
# Createa a tensor
some_tensor = torch.rand(3, 6)
some_tensor

tensor([[0.5446, 0.1074, 0.7815, 0.9639, 0.1946, 0.5064],
        [0.3750, 0.2999, 0.8375, 0.5013, 0.7506, 0.7815],
        [0.1458, 0.6369, 0.5643, 0.7153, 0.2585, 0.3036]])

In [185]:
# find the detail about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Tensor device: {some_tensor.device}")

tensor([[0.5446, 0.1074, 0.7815, 0.9639, 0.1946, 0.5064],
        [0.3750, 0.2999, 0.8375, 0.5013, 0.7506, 0.7815],
        [0.1458, 0.6369, 0.5643, 0.7153, 0.2585, 0.3036]])
Datatype of tensor : torch.float32
Shape of tensor: torch.Size([3, 6])
Tensor device: cpu


# Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subraction
* Multiplication (element - wise)
* Division
* Matrix multiplication

In [186]:
# Create a tensor and add 9 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [187]:
# multiply tensor by 9
tensor * 9

tensor([ 9, 18, 27])

In [188]:
# tensors don't change unless reassign
print(tensor)

tensor([1, 2, 3])


In [189]:
# torch built-in function
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [190]:
# element wise multiplication
torch.tensor([1, 2, 3]) * torch.tensor([1, 2, 3])

tensor([1, 4, 9])

### matrix multiplication
1. The inner dimensions must match
`(3, 2) @ (3, 2) won't work`
`(2, 3) @ (3, 2) will work`
`(3, 2) @ (2, 3) will work`
2. The resulting matrix has the shape of the outer dimension
# (2, 3) @ (3, 2) -> (2, 2)
# (3, 2) @ (2, 3) -> (3, 3)



In [191]:
tensor = torch.tensor([1, 2, 3])  

In [192]:
# Matrix multiplication
tensor @ tensor


tensor(14)

In [193]:
%%time
# matrix multiplication manual
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.89 ms, sys: 54 µs, total: 2.94 ms
Wall time: 3.48 ms


In [194]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 83 µs, sys: 0 ns, total: 83 µs
Wall time: 89.4 µs


tensor(14)

### One of the main common errors in deep learning: shape errors  

In [196]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [197]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the same of one of our tensor using a transpose.

A transponse switches the axis or dimensions of a given tensor

In [198]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [199]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [200]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [201]:
# The matrix multiplication operation is possible when tensor_B is transformed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [202]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [203]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [204]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [205]:
# find the mean - note: torch.mean() function requires a tensor of float32 datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [206]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# find the positional min and max 

In [207]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [208]:
# find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [209]:
# find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

# reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - returns a view of an input tensor of certain shape but keeps the same memory as the original tensor
* Stacking - combines multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - returns a view of the input with dimensions permuted (swapped) in a certain way

In [210]:
# create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [211]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [212]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [213]:
# changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [214]:
# stack tensors on top of each other
x_stack = torch.stack([x, x, x, x], dim=0)
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [215]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\n New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

 New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [216]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)

print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# adds an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [219]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# permute the original tensor to rearrange the axis order
x_permute = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1 ->, 2 -> 0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permute.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [222]:
x_original[0, 0, 0] = 9
x_permute

# Permute returns the view of the original tensor so changing the original tensor changes the permute tensor as well 

tensor([[[9.0000e+00, 5.2076e-01, 3.6272e-01,  ..., 2.8219e-01,
          3.7937e-01, 9.6825e-01],
         [3.1175e-01, 9.6766e-01, 7.5724e-01,  ..., 6.3876e-01,
          6.1618e-01, 6.0306e-01],
         [6.4443e-01, 6.3168e-01, 2.1911e-01,  ..., 1.0511e-01,
          2.0135e-01, 9.0330e-01],
         ...,
         [6.6437e-01, 2.6408e-01, 8.6848e-01,  ..., 3.1449e-01,
          8.8429e-03, 7.7126e-01],
         [6.2914e-02, 2.1821e-01, 3.1329e-01,  ..., 1.5857e-01,
          6.2898e-03, 5.2536e-01],
         [9.5995e-01, 7.8830e-01, 6.0144e-01,  ..., 8.1457e-01,
          2.7750e-01, 2.0647e-01]],

        [[5.1777e-01, 9.3335e-01, 2.5170e-01,  ..., 5.5335e-01,
          9.3812e-01, 7.5017e-01],
         [8.2858e-01, 3.2856e-01, 2.1536e-01,  ..., 2.3783e-02,
          6.3287e-02, 8.5005e-01],
         [5.1678e-01, 8.2862e-01, 2.7563e-02,  ..., 7.7730e-01,
          6.5420e-01, 5.1346e-01],
         ...,
         [1.0005e-01, 4.6627e-02, 8.4525e-01,  ..., 2.2440e-01,
          3.754

# Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [224]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [225]:
# index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [226]:
# index on middle
x[0][0]

tensor([1, 2, 3])

In [227]:
# index on the most inner
x[0][0][0]

tensor(1)

In [228]:
# you can also use ":" to select "all" of a target dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [229]:
# get all values of the 0 dimension but one the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [231]:
# get the index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [241]:
# index on x to return 9
x[0, 2, 2]

# index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy .> `torch.Tensor.numpy()`

In [242]:
# numpy to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [244]:
# change the value of array, what it will do to tensor
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [246]:
# tensor to numpy array
tensor = torch.ones(9)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.int32),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32))

In [247]:
# change the tensor, what happens to numpy_tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=torch.int32),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32))

## Reproducibility (trying to take random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again`

To reduce randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [253]:
import torch

# Create two random tensors
random_tensorA = torch.rand(3, 4)
random_tensorB = torch.rand(3, 4)

print(random_tensorA)
print(random_tensorB)
print(random_tensorA == random_tensorB)

tensor([[0.5171, 0.9081, 0.5075, 0.1789],
        [0.7256, 0.3007, 0.1783, 0.5682],
        [0.6104, 0.1696, 0.1449, 0.8983]])
tensor([[0.0965, 0.9744, 0.4282, 0.5487],
        [0.6068, 0.8386, 0.0397, 0.1679],
        [0.7672, 0.1614, 0.6430, 0.3324]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [263]:
# crate random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 9
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.6558, 0.3020, 0.4799, 0.7774],
        [0.9180, 0.9310, 0.2604, 0.9534],
        [0.3804, 0.4104, 0.9510, 0.5686]])
tensor([[0.6558, 0.3020, 0.4799, 0.7774],
        [0.9180, 0.9310, 0.2604, 0.9534],
        [0.3804, 0.4104, 0.9510, 0.5686]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility

* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch behind the scenes to make everything hunky dory (good)

### 1. Getting a GPU

1. Easiest - Use Google Colab for a GPU (options to upgrade)
2. Use your own GPU - take a little bit of setup and requires the investment of purchasing GPU and it has lot of options
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setup to do this refer to PyTorch setup documentation

In [2]:
!nvidia-smi

Thu Jun  8 04:09:15 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [9]:
# check GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code.
E.g. run on GPU if available, else default to CPU

In [5]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
# count number of devices
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [10]:
# create a tensor (default CPU)
import torch
tensor = torch.tensor([1, 2, 3])

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [12]:
# move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


### move tensor back to CPU

In [14]:
# if tensor is on GPU then it is not possible to transform using numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [16]:
# to fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])