<a href="https://colab.research.google.com/github/gagan0183/pytorch/blob/main/pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch fundamental

```
# This is formatted as code
```



In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introduction to tensors

### Creating tensors

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# Convert tensor to python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([9, 9])
vector

tensor([9, 9])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [20]:
# matrix
MATRIX = torch.tensor([[9, 10], [11, 12]])

In [13]:
MATRIX.ndim

2

In [19]:
MATRIX[0]

tensor([ 9, 10,  9])

In [18]:
MATRIX.shape

torch.Size([2, 3])

In [18]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [9, 5, 6],
                       [9, 9, 9 ]]])

In [15]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors ?

Random tensors are important because the way many netural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random sensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [27]:
# Creata a random tensor of size ( 1, 2)
random_tensor = torch.rand(1, 9, 9)
random_tensor

tensor([[[8.5177e-01, 2.9463e-01, 5.1872e-01, 3.2291e-01, 3.6338e-01,
          4.5563e-01, 6.6840e-01, 7.5473e-01, 5.9331e-01],
         [1.7656e-01, 4.4974e-01, 4.1502e-02, 4.8768e-01, 2.5713e-01,
          5.1293e-01, 6.9703e-01, 4.8208e-04, 9.4533e-01],
         [5.4251e-02, 2.9358e-01, 4.3947e-02, 2.1592e-01, 7.0273e-01,
          8.9004e-01, 9.9040e-01, 7.2761e-01, 7.3897e-01],
         [1.2166e-01, 1.7322e-01, 1.4463e-01, 2.9221e-01, 9.7527e-01,
          6.0432e-01, 5.1285e-01, 3.1486e-01, 8.4532e-01],
         [5.0772e-01, 6.2478e-01, 2.5327e-02, 7.6485e-01, 7.5069e-01,
          8.1725e-02, 4.0984e-01, 9.7365e-01, 4.0436e-01],
         [7.1059e-01, 5.4459e-02, 8.6219e-01, 9.6820e-01, 3.7809e-01,
          7.9747e-01, 3.6413e-01, 6.0702e-01, 9.6258e-01],
         [2.9095e-02, 3.8457e-01, 6.3001e-01, 6.7497e-01, 2.6112e-01,
          5.9948e-01, 7.9407e-01, 1.0100e-01, 6.5968e-01],
         [8.4278e-01, 5.2767e-01, 1.9638e-01, 2.0163e-01, 8.9109e-02,
          7.3318e-01, 9.674

In [28]:
random_tensor.ndim

3

In [31]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # height, width and color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [32]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (1, 9, 9))
zeros

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [33]:
zeros * random_tensor

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [35]:
# create a tensor of ones
ones = torch.ones(9, 9)
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
ones.dtype

torch.float32